POST http://localhost:7902/binV5Secured/SalesReturns/Create
Content-Type: application/json

{"ProductName":"","CostPrice":0,"ProductAliasName":"","SalePrice":0,"PercentageValueAddition":0,"UserDescription":"","SRRef":"","QrCode":""}