POST http://localhost:7902/binV5Secured/pos/Create/SendMail
Content-Type: application/json

{"BillNumber2425":0,"Date":"","CustomerName":"","ContactNumber":"","CustomerNumber":"","PaymentMode":"","GSTNumber":"","DateTime":""}